server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: PT60M
spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${r.chat.datasource.driver-class-name}
      url: jdbc:mysql://${r.chat.datasource.host}:${r.chat.datasource.port}/${r.chat.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${r.chat.datasource.username}
      password: ${r.chat.datasource.password}
  redis:
    host: ${r.chat.redis.host}
    port: ${r.chat.redis.port}
    password: ${r.chat.redis.password}
    database: ${r.chat.redis.database}
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    com:
      r:
        chat:
          mapper: debug
          service: info
          controller: info
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.r.chat.entity
  configuration:
    map-underscore-to-camel-case: true
