r:
  chat:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      port: 3306
      database: r_chat
      username: root
      password: 123456
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 9
    ws-port: 8081
    project-folder: D:/Code/JavaCode/r-chat/r-chat-data
    admin-emails:
      - 1259864733@qq.com
      - test@tt.com
