r:
  chat:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      port: 3306
      database: r_chat
      username: root
      password: 123456
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 9
    ws-port: 5051
    project-folder: D:/Code/JavaCode/r-chat/r-chat-data
    admin-emails:
      - 1259864733@qq.com
      - test@tt.com
    default-settings:
      max-group-count: 5
      max-group-member-count: 200
      max-image-size: 2
      max-video-size: 5
      max-file-size: 5
      robot-id: robot@robot.com
      robot-nick-name: Robot-Chat
      robot-welcome-msg: 欢迎使用R-Chat!
