server:
  port: 5050
  servlet:
    context-path: /api
    session:
      timeout: PT60M
spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${r.chat.datasource.driver-class-name}
      url: jdbc:mysql://${r.chat.datasource.host}:${r.chat.datasource.port}/${r.chat.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${r.chat.datasource.username}
      password: ${r.chat.datasource.password}
  redis:
    host: ${r.chat.redis.host}
    port: ${r.chat.redis.port}
    password: ${r.chat.redis.password}
    database: ${r.chat.redis.database}
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    com:
      r:
        chat:
          mapper: debug
          service: debug
          controller: debug
  file:
    name: ${r.chat.project-folder}/logs/r-chat.log
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}%clr(%X{admin}){yellow}%clr(%X{userId}){blue}%clr(%X{ws}){magenta} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} :%X{admin}%X{userId}%X{ws} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}'

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.r.chat.entity
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_empty
r:
  chat:
    app-name: ${r.chat.app-name}
    ws-port: ${r.chat.ws-port}
    heartbeat-interval: ${r.chat.heartbeat-interval}
    max-unread-chat-fetch-days: ${r.chat.max-unread-chat-fetch-days}
    project-folder: ${r.chat.project-folder}
    admin-emails: ${r.chat.admin-emails}
    id-length: ${r.chat.id-length}
    token-random-chars-length: ${r.chat.token-random-chars-length}
    default-settings:
      max-group-count: ${r.chat.default-settings.max-group-member-count}
      max-group-member-count: ${r.chat.default-settings.max-group-member-count}
      max-image-size: ${r.chat.default-settings.max-image-size}
      max-video-size: ${r.chat.default-settings.max-video-size}
      max-file-size: ${r.chat.default-settings.max-file-size}
      robot-id: ${r.chat.default-settings.robot-id}
      robot-nick-name: ${r.chat.default-settings.robot-nick-name}
      robot-welcome-msg: ${r.chat.default-settings.robot-welcome-msg}
      robot-default-reply: ${r.chat.default-settings.robot-default-reply}
