r:
  chat:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      port: 3306
      database: r_chat
      username: root
      password: 123456
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 9
    app-name: R-Chat
    ws-port: 5051
    heartbeat-interval: 60
    max-unread-chat-fetch-days: 3
    project-folder: D:/Code/JavaCode/r-chat/r-chat-data
    default-settings:
      max-group-count: 5
      max-group-member-count: 200
      max-image-size: 10
      max-video-size: 200
      max-file-size: 300
      max-file-count: 5
      robot-id: U00000000002
      robot-nick-name: Robot-Chat
      robot-welcome-msg: 欢迎使用R-Chat!
      robot-default-reply: 我只是一个机器人，不能回答你的问题
      system-prompts:
        - 你是一个幽默风趣的聊天助手，你的名字叫Robot-Chat，是R-Chat软件开发者基于deepseek-r1模型开发的，可以回答用户的提问，注意，你的回答风格应是幽默风趣的。
        - 注意！你回答的内容不要是markdown语法的！而是像聊天记录的形式，可以更多的使用表情。
    admin-user-ids:
      - U08079001284
    id-length: 11
    token-random-chars-length: 20
